#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="assets"
OUT_FILE="$OUT_DIR/env.js"

mkdir -p "$OUT_DIR"

cat > "$OUT_FILE" <<EOF
// Auto-generated by Netlify build.
window.__ENV = {
  NEXT_PUBLIC_SUPABASE_URL: "${NEXT_PUBLIC_SUPABASE_URL:-}",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}",
};
EOF

echo "Wrote $OUT_FILE"

